import type { PreDealOutcome } from "./baseline-compute";

/**
 * Pre-deal outcome of one round on a FULL shoe, under best play.
 *
 * Committed constants, not a live computation. Deriving these takes 1000 engine
 * evaluations - over a second at eight decks - and the answer never changes for a
 * given deck count, so it is generated once and locked. `baseline.test.ts` re-derives
 * the whole table from the engine and fails if any figure drifts, which is what keeps
 * a committed number honest.
 *
 * Generated by `preDealOutcome` in ./baseline-compute.ts.
 */
export const PRE_DEAL: Readonly<Record<string, PreDealOutcome>> = {
  "1": {
    win: 0.43559,
    push: 0.084627,
    loss: 0.479783,
    ev: 0.001587,
    natural: 0.048265,
    stiff: 0.387632,
  },
  "2": {
    win: 0.433973,
    push: 0.086215,
    loss: 0.479813,
    ev: -0.002204,
    natural: 0.047797,
    stiff: 0.386109,
  },
  "4": {
    win: 0.433099,
    push: 0.087024,
    loss: 0.479877,
    ev: -0.003978,
    natural: 0.047566,
    stiff: 0.385359,
  },
  "6": {
    win: 0.432799,
    push: 0.087281,
    loss: 0.479919,
    ev: -0.00456,
    natural: 0.047489,
    stiff: 0.38511,
  },
  "8": {
    win: 0.432647,
    push: 0.087417,
    loss: 0.479936,
    ev: -0.004851,
    natural: 0.047451,
    stiff: 0.384986,
  },
  infinite: {
    win: 0.431981,
    push: 0.088344,
    loss: 0.479674,
    ev: -0.005704,
    natural: 0.047337,
    stiff: 0.384615,
  },
};

/**
 * Baseline for a deck count, or null if there is no entry.
 *
 * Keyed by deck count alone: these figures describe a full shoe and do NOT track
 * discards. The UI says so rather than silently presenting a stale number - the
 * alternative is recomputing on every edit, which costs a second at eight decks.
 */
export function preDealBaseline(
  decks: number | "infinite",
): PreDealOutcome | null {
  return PRE_DEAL[String(decks)] ?? null;
}
